name: Ribbon Integratio

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  analyze_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Analyze Pull Request
        id: analyze
        run: |
          # Retrieve the pull request details using the Github API
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          PR_DESCRIPTION=$(jq --raw-output .pull_request.body "$GITHUB_EVENT_PATH")
          PR_RECIPIENT=$(jq --raw-output .pull_request.user.email "$GITHUB_EVENT_PATH")

          # Create the Ribbon Award JSON
          RIBBON_AWARD=$(jq -n --arg recipient "$PR_RECIPIENT" --arg title "$PR_TITLE" --arg description "$PR_DESCRIPTION" --arg additional_description "Additional description" '{"recipient": $recipient, "title": $title, "description": $description, "additional_description": $additional_description}')

          # Output the Ribbon Award JSON
          echo "::set-output name=ribbon_award::$RIBBON_AWARD"
