name: Create Ribbon Awards

on:
  pull_request:
    types:
      - opened

jobs:
  create_ribbon_awards:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create ribbon_awards directory and ribbon_file.json
      run: |
        mkdir -p ribbon_awards
        echo '{}' > ribbon_awards/ribbon_file.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ribbon_awards/ribbon_file.json
        git commit -m "Create ribbon_awards directory and ribbon_file.json"
        git push
